# Generated by Django 5.1.1 on 2024-11-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange",
                    models.IntegerField(
                        choices=[(1, "NSE"), (2, "NFO")], verbose_name="Exchange"
                    ),
                ),
                (
                    "symboltoken",
                    models.CharField(max_length=100, verbose_name="Symbol Token"),
                ),
                (
                    "tradingsymbol",
                    models.CharField(max_length=100, verbose_name="Trading Symbol"),
                ),
                (
                    "variety",
                    models.IntegerField(
                        choices=[(1, "NORMAL"), (2, "BO"), (3, "CO")],
                        verbose_name="Variety",
                    ),
                ),
                (
                    "transactiontype",
                    models.IntegerField(
                        choices=[(1, "BUY"), (2, "SELL")],
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "ordertype",
                    models.IntegerField(
                        choices=[
                            (1, "MARKET"),
                            (2, "LIMIT"),
                            (3, "STOPLOSS_LIMIT"),
                            (4, "STOPLOSS_MARKET"),
                        ],
                        verbose_name="Order Type",
                    ),
                ),
                (
                    "producttype",
                    models.IntegerField(
                        choices=[
                            (1, "DELIVERY"),
                            (2, "CARRYFORWARD"),
                            (3, "MARGIN"),
                            (4, "INTRADAY"),
                            (5, "BO"),
                        ],
                        verbose_name="Product Type",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        choices=[(1, "DAY"), (2, "IOC")], verbose_name="Duration"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                ("is_live", models.BooleanField(default=True)),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Close Price",
                    ),
                ),
                (
                    "close_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Close Date"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=200)),
                ("symboltoken", models.CharField(max_length=200)),
            ],
        ),
    ]
