# Generated by Django 5.1.3 on 2025-01-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="papertrade",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="papertrade",
            name="exchange",
        ),
    ]
